#!/bin/bash --login

#SBATCH --job-name HyPhy
#SBATCH --partition=cpu
#SBATCH --array=1-1%1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBTACH --mem-per-cpu=6G
#SBATCH --output=%A_%a.out
#SBATCH --error=%A_%a.err
#SBATCH --time 0-48:00:00

module load gcc

conda activate ~/myproject_envs/hyphy-2.5.6x/


#Array indexing
#og=$(sed -n "$SLURM_ARRAY_TASK_ID"p og_list_sorted.txt)

#echo `(echo $og"_cds_hammer.fa"; echo $og"_cds_hammer.fa.treefile") | hyphy meme`

hyphy ../hyphy-analyses/FitMG94/FitMG94.bf \
  --alignment 7571_cds_treeinput.fa \
  --tree 7571_generax_complete.nwk \
  --type local \
  --rooted Yes \
  --lrt Yes \
  --output fitmg94.local.json \
  --save-fit fitmg94.local.fit \
